const fs = require('fs');
let code = fs.readFileSync('src/components/TabAOF.tsx', 'utf8');

code = code.replace(/<input type="number" \s*\r?\n\s*value=\{aofCiele\.zakladnaRezerva \|\| ''\} \s*\r?\n\s*onChange=\{\(e\) => setAofCiele\(\{zakladnaRezerva: Number\(e\.target\.value\) \|\| ''\}\)\} \s*\r?\n\s*className="w-2\/3 border px-2 text-center bg-white dark:bg-\[#111\]" placeholder="23 950 €" \/>/g, `<input type="text" readOnly value={vypocitanaRezerva > 0 ? \`\${vypocitanaRezerva.toFixed(0)} €\` : ''} className="w-2/3 border px-2 text-center bg-transparent cursor-default font-bold text-[#AB0534]" placeholder="23 950 €" />`);

code = code.replace(/<div className="grid grid-cols-3 items-center mb-1"><div className="font-bold">\{t\('aof.produkcnyKapital'\)\}<\/div><input value=\{aofCiele.zabezpecenieKlientKapital\} onChange=\{e=>setAofCiele\(\{zabezpecenieKlientKapital: Number\(e.target.value\)\}\)\} className="border mx-1 px-1 text-center" \/><input value=\{aofCiele.zabezpeceniePartnerKapital\} onChange=\{e=>setAofCiele\(\{zabezpeceniePartnerKapital: Number\(e.target.value\)\}\)\} className="border mx-1 px-1 text-center" \/><\/div>/g, `<div className="grid grid-cols-3 items-center mb-1"><div className="font-bold">{t('aof.produkcnyKapital')}</div><input type="text" readOnly value={vypocitanyProdukcnyKapitalKlient > 0 ? \`\${vypocitanyProdukcnyKapitalKlient.toFixed(0)} €\` : ''} className="border mx-1 px-1 text-center bg-transparent cursor-default" /><input type="text" readOnly value={vypocitanyProdukcnyKapitalPartner > 0 ? \`\${vypocitanyProdukcnyKapitalPartner.toFixed(0)} €\` : ''} className="border mx-1 px-1 text-center bg-transparent cursor-default" /></div>`);

code = code.replace(/<div className="grid grid-cols-3 items-center mb-2"><div className="text-right pr-2">\{t\('aof.naDobu'\)\}<\/div><div className="mx-1 relative"><input value=\{aofCiele.zabezpecenieKlientRentaRoky\} onChange=\{e=>setAofCiele\(\{zabezpecenieKlientRentaRoky: Number\(e.target.value\)\}\)\} className="border w-full px-1 text-center pr-8" \/><span className="absolute right-2 top-0">\{t\('aof.rocna'\)\}<\/span><\/div><div className="mx-1 relative"><input value=\{aofCiele.zabezpeceniePartnerRentaRoky\} onChange=\{e=>setAofCiele\(\{zabezpeceniePartnerRentaRoky: Number\(e.target.value\)\}\)\} className="border w-full px-1 text-center pr-8" \/><span className="absolute right-2 top-0">\{t\('aof.rocna'\)\}<\/span><\/div><\/div>/g, `<div className="grid grid-cols-3 items-center mb-2"><div className="text-right pr-2">{t('aof.naDobu')}</div><div className="mx-1"><select value={aofCiele.zabezpecenieKlientRentaRoky} onChange={e=>setAofCiele({zabezpecenieKlientRentaRoky: e.target.value})} className="border w-full px-1 text-center bg-white dark:bg-[#111] py-1"><option value="20-ročná">20-ročná</option><option value="doživotná">doživotná</option></select></div><div className="mx-1"><select value={aofCiele.zabezpeceniePartnerRentaRoky} onChange={e=>setAofCiele({zabezpeceniePartnerRentaRoky: e.target.value})} className="border w-full px-1 text-center bg-white dark:bg-[#111] py-1"><option value="20-ročná">20-ročná</option><option value="doživotná">doživotná</option></select></div></div>`);

fs.writeFileSync('src/components/TabAOF.tsx', code);
console.log('done');
